import Head from "next/head";
import Image from "next/image";
import BottomBar from "../components/BottomBar";
import MainScreen from "../components/MainScreen";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Socal Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <MainScreen />
      <BottomBar />
    </div>
  );
}
